export enum OutComeEnum {
  firstFighterWins,
  secondFighterWins,
  firstFighterByKnockoutOrDisqualification,
  secondFighterByKnockoutOrDisqualification,
  firstFighterByDecision,
  secondFighterByDecision,
  firstFighterBySubmission,
  secondFighterBySubmission,
  firstFighterInRound1,
  firstFighterInRound2,
  firstFighterInRound3,
  firstFighterInRound4,
  firstFighterInRound5,
  secondFighterInRound1,
  secondFighterInRound2,
  secondFighterInRound3,
  secondFighterInRound4,
  secondFighterInRound5,
  fightLastsMoreThanOneAndHalfRounds,
  fightLastsLessThanOneAndHalfRounds,
  fightLastsMoreThanThreeOneAndHalfRounds,
  fightLastsLessThanThreeOneAndHalfRounds,
  fightLastsMoreThanFourAndHalfRounds,
  fightLastsLessThanFourAndHalfRounds,
}

export const OutComeLabel = new Map<number, string>([
    [OutComeEnum.firstFighterWins, "First Fighter wins"],
    [OutComeEnum.secondFighterWins, "Second Fighter wins"],
    [OutComeEnum.firstFighterByKnockoutOrDisqualification, "First Fighter wins by K.O."],
    [OutComeEnum.secondFighterByKnockoutOrDisqualification, "Second Fighter wins by K.O."],
    [OutComeEnum.firstFighterByDecision, "First Fighter wins by Decision"],
    [OutComeEnum.secondFighterByDecision, "Second Fighter wins by Decision"],
    [OutComeEnum.firstFighterBySubmission, "First Fighter wins by Submission"],
    [OutComeEnum.secondFighterBySubmission, "Second Fighter wins by Submission"],
    [OutComeEnum.firstFighterInRound1, "First Fighter wins in Round 1"],
    [OutComeEnum.firstFighterInRound2, "First Fighter wins in Round 2"],
    [OutComeEnum.firstFighterInRound3, "First Fighter wins in Round 3"],
    [OutComeEnum.firstFighterInRound4, "First Fighter wins in Round 4"],
    [OutComeEnum.firstFighterInRound5, "First Fighter wins in Round 5"],
    [OutComeEnum.secondFighterInRound1, "Second Fighter wins in Round 1"],
    [OutComeEnum.secondFighterInRound2, "Second Fighter wins in Round 2"],
    [OutComeEnum.secondFighterInRound3, "Second Fighter wins in Round 3"],
    [OutComeEnum.secondFighterInRound4, "Second Fighter wins in Round 4"],
    [OutComeEnum.secondFighterInRound5, "Second Fighter wins in Round 5"],
    [OutComeEnum.fightLastsMoreThanOneAndHalfRounds, "Fight lasts more than 1.5 rounds"],
    [OutComeEnum.fightLastsLessThanOneAndHalfRounds, "Fight lasts less than 1.5 rounds"],
    [OutComeEnum.fightLastsMoreThanThreeOneAndHalfRounds, "Fight lasts more than 3.5 rounds"],
    [OutComeEnum.fightLastsLessThanThreeOneAndHalfRounds, "Fight lasts less than 3.5 rounds"],
    [OutComeEnum.fightLastsMoreThanFourAndHalfRounds, "Fight lasts more than 4.5 rounds"],
    [OutComeEnum.fightLastsLessThanFourAndHalfRounds, "Fight lasts less than 4.5 rounds"]
]);
